server:
  port: 9071
spring:
  application:
    name: "payments"
  datasource:
    url: jdbc:mysql://localhost:3309/paymentsdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  Kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false


    consumer:
      group-id: group-payments
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.booking.payments.dto.ProcessingDto
    admin:
      auto-create: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

stripe:
  api-key: ${API_KEY}
  webhook-key : ${WEBHOOK_KEY}
  success-url: http://localhost:9071/api/paymentSuccess?session_id={CHECKOUT_SESSION_ID}
  cancel-url: http://localhost:9071/api/paymentCancel?session_id={CHECKOUT_SESSION_ID}
