server:
  port: 8270
spring:
  application:
    name: "ticketBooking"
  datasource:
    url: jdbc:mysql://localhost:3308/bookingsdb
    username: root
    password: root
  sql:
    init:
      mode: always
  jpa:
    show-sql: false
  Kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false


    consumer:
      group-id: group-booking
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.booking.ticketBooking.dto.ProcessingDto
    admin:
      auto-create: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka